name: Kong Plugin Deploy

on:
  push:
    branches: 
      - main
      - master
      - cicdupdate
  pull_request_review:
    branches: 
      - main
      - master
    types:
      - submitted

env:
  EKS_CLUSTER_NAME: aries-default
  AWS_REGION: af-south-1

jobs:
  Release:
    if: github.ref_name	== 'master' || github.ref_name	== 'main' || github.ref_name	== 'cicdupdate' 

    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: AWS Login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      -
        name: Deploy tenant-apikey plugin
        run: |
          aws eks --region "${AWS_REGION}" update-kubeconfig --name "${EKS_CLUSTER_NAME}"
          kubectl create configmap tenant-apikey --from-file=plugins/tenant-apikey -n app